# Generated by Django 3.2.7 on 2021-09-12 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(max_length=500)),
                ('depintake', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=50)),
                ('sturollno', models.IntegerField()),
                ('stuaddress', models.CharField(max_length=100)),
                ('stumarks', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_rel.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecname', models.CharField(max_length=100)),
                ('lecsal', models.FloatField()),
                ('lecsub', models.CharField(max_length=30)),
                ('department', models.ManyToManyField(to='college_rel.Department')),
            ],
        ),
    ]
